### ISSUE TITLE
How do I enable wine-staging or wine 6.0

### ISSUE THREAD

**Issue by kiwidoggie** [scottyhardy/docker-wine#107]
I was wondering how to enable wine-staging or wine-6.0 or newer in this container. Thanks

**Comment by patthiel** [comment]
Looks like you can specify the `unstable` as the WINE_BRANCH build arg here https://github.com/scottyhardy/docker-wine/blob/master/Dockerfile#L27 . 

You'll have to build the docker image yourself, and when calling `./docker-wine` you'll have to add the `--local` flag: https://github.com/scottyhardy/docker-wine/blob/master/docker-wine#L10

i've not tried this, but it looks like it should work

**Comment by scottyhardy** [comment]
Hi @kiwidoggie, thanks for your interest in my project :) I've set up automated builds for the stable and devel branches, with the stable branch used as default and tagged with latest.  To use the latest devel build, you can either specify the tag `scottyhardy/docker-wine:devel` with your `docker run` command, or if you're using the docker-wine script: `./docker-wine --tag=devel`

I don't do builds using the staging branch due to its instability and constant changes, but you can build it yourself by adding `--build-arg="WINE_BRANCH=staging"` to your `docker-build` command.  Or, if you prefer my canned scripts, you can use: `WINE_BRANCH=staging ./build` to build your image, then run your container with `./docker-wine --local`

Thanks for the question, I might add a mention of these build options to my README.md in a future release

**Comment by kiwidoggie** [comment]
Thank you very much <3
