### ISSUE TITLE
Latest images black screen on RDP

### ISSUE THREAD

**Issue by brandonros** [scottyhardy/docker-wine#137]
Something about sudo, as per @scottyhardy himself here: https://github.com/scottyhardy/docker-wine/issues/109#issuecomment-999332775

Made a ticket for you/us so I can track when to try stuff again.

**Comment by scottyhardy** [comment]
Sorry, I should have mentioned I've already solved this issue here https://github.com/scottyhardy/docker-wine/pull/136, but I suppose I didn't document much about my findings.

I'm not exactly sure why, but the only thing that would trigger this problem with the black screen to occur would be when the `wineuser` account was added to the `sudo` group and only on the ARM based image. I had no issues with Intel images on my Intel Mac.  Where again, with your Apple M1 Mac I believe you only experienced issues with the Intel image?

Anyway, I would start the container with `./docker-wine --rm --arm64 --rdp` then ran `top` in the bash shell.  I then connected to the container via RDP and after logging in, the command `systemctl` was running at 100%. Long story short, I removed the `systemd` package and the problem went away.

The `systemd` package was being installed as a required package for `software-properties-common` (so even trying to prevent the package being installed with [pinning](https://unix.stackexchange.com/questions/459162/how-to-mark-a-package-to-prevent-from-being-installed) didn't work), which in turn is required for adding the wine repository.  My solution  https://github.com/scottyhardy/docker-wine/pull/136/commits/557429d52e1c218ca4fbc67e4a1362cf8e29fe3a in the end is a little hacky as I add then remove the software-properties-common package, then also need to remove the systemd packages as otherwise they're left behind.  There's probably a more elegant solution, but I'm happy enough with this workaround for now.

Anyways, please check the `latest` and `arm64` tagged images to test out the Intel and ARM images respectively.  If it works from your end then we can go ahead and close this issue

**Comment by scottyhardy** [comment]
Actually, I wasn't a fan of adding and removing software-properties-common and it was installing quite a bit for just a couple of helper scripts that weren't even necessary, so it's now removed completely.
