### ISSUE TITLE
Network access

### ISSUE THREAD

**Issue by paulocheque** [scottyhardy/docker-wine#60]
Hi there, 

I want to initialize the Docker container with the same network as the Host machine (using the active VPN network).

Then, my Windows programs will be able to use this network.

It appears the docker-wine container doesn't have network configured. Is that true?

I tried to edit the `docker-wine` script and put a `--network=host` there. Also I tried to install `ping` and `ping www.google.com` but no success.

Is there an option to fix that without changing the script? Or any workaround for the moment?

Thanks in advance

**Comment by scottyhardy** [comment]
Hi @paulocheque 

I don’t define any network settings, so it just uses the Docker NAT for network connection and the port for RDP is explicitly forwarded to the container for incoming traffic using `--publish=3389:3389/tcp`.  This should enable any outgoing traffic like pings, apt-get updates and installs, etc. I don’t currently pass through network options with the docker-wine script but the change required would be to simply add it to the `case` block that parses the command line - I’ll add that soon.

I suspect your problem is the VPN you mentioned and I would start my troubleshooting there.  You may be able to configure your VPN to allow connection to local networks but otherwise I think you’re right and using `--network=host` should solve it.

**Comment by scottyhardy** [comment]
Ok @paulocheque I've added the `--network=*` passthrough to the docker-wine script.  If you download the latest version you can just add `--network=host` to the `./docker-wine` command

**Comment by paulocheque** [comment]
Awesome, I will give it a try, thanks for the quick answer and action!

**Comment by mpielke** [comment]
Good afternoon,

just an idea to add to this issue: could you also include the --ip as passthrough in the script?

I wanted to create a container with a specific IP address in a specific docker network (subnet), so that I know how to access the container externally at any time. Using the --network passthrough, I was able to assign the network but I could not assign the ip address. I have manually added this passthrough into the script and it works just fine - maybe others run into the same issue.

Thanks for your great work on this docker, it really helped me solving some issues!

Regards
