### ISSUE TITLE
Not running on ubuntu 20.04

### ISSUE THREAD

**Issue by loeffel-io** [scottyhardy/docker-wine#77]
Fresh installed ubuntu 20.04

```bash
	docker run -it \
		--rm \
		--env="DISPLAY" \
		--volume="${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:ro" \
		--volume="/tmp/.X11-unix:/tmp/.X11-unix" \
		--volume="winehome:/home/wineuser" \
		--hostname="$(hostname)" \
		--name="wine" \
		scottyhardy/docker-wine wine notepad
```

result: 

```bash
docker run -it \
        --rm \
        --env="DISPLAY" \
        --volume=":/root/.Xauthority:ro" \
        --volume="/tmp/.X11-unix:/tmp/.X11-unix" \
        --volume="winehome:/home/wineuser" \
        --hostname="" \
        --name="wine" \
        scottyhardy/docker-wine wine notepad
No protocol specified
0010:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0010:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0010:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0010:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0010:err:ole:get_local_server_stream Failed: 80004002
0009:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0009:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
make: *** [Makefile:5: run] Fehler 1
```

**Comment by loeffel-io** [comment]
`xhost +` solved the issue but i think this is not the correct solution, right? would love to get some help!

**Comment by scottyhardy** [comment]
Yeah, I’d prefer not to resort to using xhost unless completely necessary as it’s less secure than using the same MIT magic cookie.  I notice in the result window that your docker run command is missing the variables for the hostname and .Xauthority - that’s 2 of the 3 components (the other being DISPLAY) required for using the local X server.  So, just confirm your docker run matches the first one you wrote as I think that one should work, or even try the docker-wine script.

Otherwise, I’ll need to run up a 20.04 VM and give it a test.

**Comment by scottyhardy** [comment]
Ok, I've just tested and can confirm I can replicate this issue.  I'll get back to you once I've found a solution.

**Comment by loeffel-io** [comment]
Thanks!

**Comment by scottyhardy** [comment]
Thanks for reporting the issue @loeffel-io - this bug was affecting all Linux varieties but is now sorted out.
